### ISSUE TITLE
Missing required architecture x86_64

### ISSUE THREAD

**Issue by GavinRooney** [saasquatch/mobile-sdk-objectivec-cocoapod#1]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Saasquatch", referenced from:
      objc-class-ref in SaaSquatchUtil.o

missing required architecture x86_64

Can not run on simulators. Can you please include

**Comment by hayward-saasquatch** [comment]
Hello Gavin,

Thanks for reaching out to us about out iOS SDK.

The saasquatch framework, as well as the sample app, have been designed to run on a physical iOS device and supports a deployment target of iOS 8.0 or above. 

Further information about testing with the saasquatch framework can be found in our [quickstart guide](https://docs.referralsaasquatch.com/mobile/ios/quickstart/#testing).

Please let us know if this brings up any further questions.

**Comment by GavinRooney** [comment]
Hi Hayward,
The result of using your sdk is that I can not test my app on different device types. I do not own all device types with all screen sizes with all versions of iOS installed so this is preventing me from developing while using your sdk. 
I do not need to test the sdk itself but I need to test every other aspect of the app as it is being developed. 
This also prevents anyone from running any form of automated testing without having physical devices attached. It seems strange that this would be done by design. 
Why is your sdk designed not to run on a simulator?

Cheers
Gav

**Comment by hayward-saasquatch** [comment]
[Version 2.0](https://github.com/saasquatch/mobile-sdk-objectivec-cocoapod/releases/tag/v.2.0) has be built as a universal framework and is now compatible with being included in apps being built for physical devices and emulators.

**Comment by GavinRooney** [comment]
This should not be closed so that new users can see that they can not run on simulator and devices with the same sdk. This is important when deciding to use your product. 

After months of having to switch in and out sdks I am so sick of it. 1 from cocoapods and 1 embedded depending on if I want to run on device or simulator. 

Please understand that this product is not mobile ready. Version 2.0 in above link runs on simulators only
